# Generated by Django 4.2.9 on 2024-02-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(default='none', max_length=20)),
                ('model', models.CharField(max_length=30, unique=True)),
                ('engine', models.CharField(choices=[('diesel', 'DIESEL'), ('gasoline', 'GASOLINE')], default='diesel', max_length=10)),
                ('horsepower', models.PositiveIntegerField(default=0)),
                ('torque', models.PositiveIntegerField(default=0)),
                ('car_type', models.CharField(choices=[('Sedan', 'sedan'), ('Coupe', 'coupe'), ('Hatchback', 'hatchback'), ('Minivan', 'minivan'), ('Electric', 'electric')], default='sedan', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('Red', 'red'), ('Blue', 'blue'), ('Yellow', 'yellow'), ('Green', 'green'), ('Black', 'black'), ('White', 'white'), ('Cyan', 'cyan')], default='black', max_length=10)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_car', to='customer.customer')),
                ('dealer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_car', to='dealer.dealer')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_car', to='car.carspecification')),
                ('vendor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_car', to='vendor.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
