# Generated by Django 4.2.9 on 2024-02-08 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_cars_customer_cars_dealer_cars_price_cars_vendor_and_more'),
        ('history', '0002_rename_date_created_customerdealerhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdealerhistory',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdealerhistory',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customerdealerhistory',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealervendorhistory',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealervendorhistory',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dealervendorhistory',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
