# Generated by Django 4.2.9 on 2024-01-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
