# Generated by Django 4.2.9 on 2024-02-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_rename_date_created_dealer_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealersCar',
        ),
    ]
