# Generated by Django 5.0 on 2024-01-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carspecification_horsepower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carspecification',
            old_name='name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_type',
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='brand',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'sedan'), ('Coupe', 'coupe'), ('Hatchback', 'hatchback'), ('Minivan', 'minivan'), ('Electric', 'electric')], default='sedan', max_length=20),
        ),
    ]
