# Generated by Django 5.0.1 on 2024-01-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_name_carspecification_model_remove_cars_brand_and_more'),
        ('customer', '0005_alter_customer_options_alter_customer_managers_and_more'),
        ('dealer', '0002_delete_dealerscar'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_car', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='cars',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_car', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='cars',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_car', to='vendor.vendor'),
        ),
    ]
