# Generated by Django 4.2.9 on 2024-01-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_delete_dealerscar'),
        ('customer', '0005_alter_customer_options_alter_customer_managers_and_more'),
        ('vendor', '0001_initial'),
        ('cars', '0005_cars_customer_cars_dealer_cars_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_car', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_car', to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_car', to='vendor.vendor'),
        ),
    ]
