# Generated by Django 4.2.9 on 2024-01-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_cars_customer_alter_cars_dealer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='carspecification',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carspecification',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='vendor',
        ),
    ]
