# Generated by Django 4.2.9 on 2024-02-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_delete_dealerscar'),
        ('vendor', '0002_rename_date_created_vendor_created_at_and_more'),
        ('customer', '0006_rename_date_created_customer_created_at_and_more'),
        ('cars', '0007_rename_date_created_cars_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_car', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='cars',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_car', to='dealer.dealer'),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_car', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='engine',
            field=models.CharField(choices=[('diesel', 'DIESEL'), ('gasoline', 'GASOLINE')], default='diesel', max_length=10),
        ),
    ]
